# Generated by Django 3.2.9 on 2021-11-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_shopuserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='shopuserprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('W', 'Женский'), ('O', 'Пол не указан')], default='O', max_length=1, verbose_name='Пол'),
        ),
    ]
